package vini.evictmap;

import arc.util.noise.Simplex;
import mindustry.Vars;
import mindustry.content.Blocks;
import mindustry.world.Block;
import mindustry.world.Tile;

import java.util.ArrayDeque;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.PriorityQueue;
import java.util.Random;
import java.util.Set;

/**
 * Evict-style resource generator: global coherent noise fields with small
 * per-room safety corrections.
 *
 * Main appearance:
 * - resources are generated by coherent noise across the whole map
 * - scale controls patch size
 * - threshold controls rarity
 *
 * Fairness corrections:
 * - every normal hex receives at least two water patches
 * - every normal hex receives copper, lead, coal, titanium, thorium and scrap
 *
 * The corrections are only used where the global noise missed a resource.
 * They pick local noise maxima and grow along the same noise field instead of
 * stamping rectangles, so the visual style remains close to the global noise.
 */
final class ResourceGenerator {

    // ---------------------------------------------------------------------
    // Independent seed stream
    // ---------------------------------------------------------------------

    private static final long RESOURCE_SEED_XOR = 0x4f52452d45564943L;

    // ---------------------------------------------------------------------
    // Placement masks
    // ---------------------------------------------------------------------

    /**
     * Ores may approach room edges, but are only placed on open Dark Sand.
     */
    private static final int ORE_MAX_RADIUS = 39;
    private static final int ORE_MAX_RADIUS_SQUARED =
        ORE_MAX_RADIUS * ORE_MAX_RADIUS;

    /**
     * Safety correction searches remain farther inside the room so every
     * guaranteed fallback patch clearly belongs to one hex.
     */
    private static final int GUARANTEE_ORE_RADIUS = 31;
    private static final int GUARANTEE_ORE_RADIUS_SQUARED =
        GUARANTEE_ORE_RADIUS * GUARANTEE_ORE_RADIUS;

    private static final int ORE_CORE_SAFE_RADIUS = 4;
    private static final int ORE_CORE_SAFE_RADIUS_SQUARED =
        ORE_CORE_SAFE_RADIUS * ORE_CORE_SAFE_RADIUS;

    /**
     * Water and tar stay away from narrow room connections.
     */
    private static final int LIQUID_MAX_RADIUS = 31;
    private static final int LIQUID_MAX_RADIUS_SQUARED =
        LIQUID_MAX_RADIUS * LIQUID_MAX_RADIUS;

    private static final int LIQUID_CORE_SAFE_RADIUS = 9;
    private static final int LIQUID_CORE_SAFE_RADIUS_SQUARED =
        LIQUID_CORE_SAFE_RADIUS * LIQUID_CORE_SAFE_RADIUS;

    // ---------------------------------------------------------------------
    // Global noise presets
    // ---------------------------------------------------------------------

    /**
     * 0.4.2 patch sizes looked good, but everything was too rare.
     * Keep the scales and lower only the thresholds.
     *
     * Scrap is intentionally close to coal.
     */
    private static final NoisePreset[] ORE_PRESETS = new NoisePreset[]{
        new NoisePreset(Blocks.oreCopper,   101, 34.0f, 0.792f, 2f, 0.30f, 0.00f),
        new NoisePreset(Blocks.oreLead,     211, 33.0f, 0.800f, 2f, 0.30f, 0.00f),
        new NoisePreset(Blocks.oreCoal,     307, 30.0f, 0.815f, 2f, 0.32f, 0.00f),
        new NoisePreset(Blocks.oreScrap,    353, 30.0f, 0.817f, 2f, 0.32f, 0.00f),
        new NoisePreset(Blocks.oreTitanium, 401, 27.0f, 0.837f, 2f, 0.30f, 0.00f),
        new NoisePreset(Blocks.oreThorium,  503, 27.5f, 0.845f, 2f, 0.30f, 0.00f)
    };

    private static final NoisePreset WATER_PRESET =
        new NoisePreset(Blocks.darksandWater, 701, 24.0f, 0.885f, 2f, 0.38f, 0.00f);

    private static final NoisePreset TAR_PRESET =
        new NoisePreset(Blocks.tar, 809, 21.0f, 0.935f, 2f, 0.35f, 0.00f);

    // ---------------------------------------------------------------------
    // Safety correction settings
    // ---------------------------------------------------------------------

    private static final int MIN_WATER_PATCHES_PER_HEX = 2;
    private static final int WATER_FALLBACK_MIN_SIZE = 5;
    private static final int WATER_FALLBACK_MAX_SIZE = 10;
    private static final int WATER_FALLBACK_MAX_LOCAL_RADIUS = 3;
    private static final int WATER_PATCH_SEPARATION = 7;
    private static final int WATER_PATCH_SEPARATION_SQUARED =
        WATER_PATCH_SEPARATION * WATER_PATCH_SEPARATION;

    private static final int ORE_FALLBACK_MIN_SIZE = 6;
    private static final int ORE_FALLBACK_MAX_SIZE = 10;
    private static final int ORE_FALLBACK_MAX_LOCAL_RADIUS = 4;

    private static final int[][] DIRECTIONS_4 = new int[][]{
        {0, -1},
        {-1, 0}, {1, 0},
        {0, 1}
    };

    private static final int[][] DIRECTIONS_8 = new int[][]{
        {-1, -1}, {0, -1}, {1, -1},
        {-1,  0},          {1,  0},
        {-1,  1}, {0,  1}, {1,  1}
    };

    private ResourceGenerator() {
    }

    static Summary generate(long mapSeed, List<HexCenter> centers) {
        int seed = foldSeed(mapSeed ^ RESOURCE_SEED_XOR);
        Random correctionRandom = new Random(mapSeed ^ 0x464149522d455649L);
        CorrectionCounter corrections = new CorrectionCounter();

        /**
         * Floors first:
         * - water and tar replace Dark Sand
         * - tar does not overwrite water
         */
        generateFloorNoise(seed, centers, WATER_PRESET);
        ensureMinimumWaterPatches(
            seed,
            correctionRandom,
            centers,
            corrections
        );

        generateFloorNoise(seed, centers, TAR_PRESET);

        /**
         * Ores afterward:
         * - each ore uses its own map-wide field
         * - later presets may overwrite earlier overlays naturally
         */
        for (NoisePreset preset : ORE_PRESETS) {
            generateOreNoise(seed, centers, preset);
        }

        ensureEveryHexHasEveryOre(
            seed,
            correctionRandom,
            centers,
            corrections
        );

        return summarizeWorld(corrections);
    }

    static String presetDescription() {
        return "global noise resources + 2 water patches and all 6 ores guaranteed per normal hex";
    }

    // ---------------------------------------------------------------------
    // Global noise generation
    // ---------------------------------------------------------------------

    private static void generateFloorNoise(
        int seed,
        List<HexCenter> centers,
        NoisePreset preset
    ) {
        int width = Vars.world.width();
        int height = Vars.world.height();

        for (int y = 0; y < height; y++) {
            for (int x = 0; x < width; x++) {
                Tile tile = Vars.world.tile(x, y);

                if (
                    tile == null
                        || tile.block() != Blocks.air
                        || tile.floor() != Blocks.darksand
                        || !insideLiquidMask(x, y, centers)
                ) {
                    continue;
                }

                if (sample(seed, preset, x, y) > preset.threshold) {
                    Tile.setFloor(tile, preset.block, Blocks.air);
                }
            }
        }
    }

    private static void generateOreNoise(
        int seed,
        List<HexCenter> centers,
        NoisePreset preset
    ) {
        int width = Vars.world.width();
        int height = Vars.world.height();

        for (int y = 0; y < height; y++) {
            for (int x = 0; x < width; x++) {
                Tile tile = Vars.world.tile(x, y);

                if (
                    tile == null
                        || tile.block() != Blocks.air
                        || tile.floor() != Blocks.darksand
                        || !insideOreMask(x, y, centers)
                ) {
                    continue;
                }

                if (sample(seed, preset, x, y) > preset.threshold) {
                    tile.setOverlay(preset.block);
                }
            }
        }
    }

    // ---------------------------------------------------------------------
    // Water guarantee
    // ---------------------------------------------------------------------

    private static void ensureMinimumWaterPatches(
        int seed,
        Random random,
        List<HexCenter> centers,
        CorrectionCounter corrections
    ) {
        for (HexCenter center : centers) {
            int attempts = 0;

            while (
                countWaterPatches(center) < MIN_WATER_PATCHES_PER_HEX
                    && attempts++ < 6
            ) {
                TilePoint start = bestWaterFallbackStart(seed, center);

                if (start == null) {
                    break;
                }

                int targetSize = inclusiveRandom(
                    random,
                    WATER_FALLBACK_MIN_SIZE,
                    WATER_FALLBACK_MAX_SIZE
                );

                int placed = growFloorPatch(
                    seed,
                    WATER_PRESET,
                    center,
                    start,
                    Blocks.darksandWater,
                    targetSize,
                    WATER_FALLBACK_MAX_LOCAL_RADIUS
                );

                if (placed == 0) {
                    break;
                }

                corrections.waterFallbackPatches++;
            }
        }
    }

    private static int countWaterPatches(HexCenter center) {
        Set<TilePoint> visited = new HashSet<>();
        int patches = 0;

        for (
            int y = center.y - LIQUID_MAX_RADIUS;
            y <= center.y + LIQUID_MAX_RADIUS;
            y++
        ) {
            for (
                int x = center.x - LIQUID_MAX_RADIUS;
                x <= center.x + LIQUID_MAX_RADIUS;
                x++
            ) {
                TilePoint point = new TilePoint(x, y);

                if (
                    visited.contains(point)
                        || !insideLiquidMaskForCenter(x, y, center)
                        || !isWater(point)
                ) {
                    continue;
                }

                patches++;
                floodWaterPatch(center, point, visited);

                if (patches >= MIN_WATER_PATCHES_PER_HEX) {
                    return patches;
                }
            }
        }

        return patches;
    }

    private static void floodWaterPatch(
        HexCenter center,
        TilePoint start,
        Set<TilePoint> visited
    ) {
        ArrayDeque<TilePoint> queue = new ArrayDeque<>();
        queue.add(start);
        visited.add(start);

        while (!queue.isEmpty()) {
            TilePoint current = queue.removeFirst();

            for (int[] direction : DIRECTIONS_4) {
                TilePoint next = new TilePoint(
                    current.x + direction[0],
                    current.y + direction[1]
                );

                if (
                    !visited.contains(next)
                        && insideLiquidMaskForCenter(next.x, next.y, center)
                        && isWater(next)
                ) {
                    visited.add(next);
                    queue.addLast(next);
                }
            }
        }
    }

    private static TilePoint bestWaterFallbackStart(
        int seed,
        HexCenter center
    ) {
        TilePoint best = null;
        float bestNoise = -Float.MAX_VALUE;

        for (
            int y = center.y - LIQUID_MAX_RADIUS;
            y <= center.y + LIQUID_MAX_RADIUS;
            y++
        ) {
            for (
                int x = center.x - LIQUID_MAX_RADIUS;
                x <= center.x + LIQUID_MAX_RADIUS;
                x++
            ) {
                TilePoint point = new TilePoint(x, y);

                if (
                    canStartWaterFallback(point, center)
                        && farEnoughFromExistingWater(point, center)
                ) {
                    float noise = sample(seed, WATER_PRESET, x, y);

                    if (noise > bestNoise) {
                        bestNoise = noise;
                        best = point;
                    }
                }
            }
        }

        return best;
    }

    private static boolean canStartWaterFallback(
        TilePoint point,
        HexCenter center
    ) {
        Tile tile = Vars.world.tile(point.x, point.y);

        return tile != null
            && tile.block() == Blocks.air
            && tile.floor() == Blocks.darksand
            && insideLiquidMaskForCenter(point.x, point.y, center);
    }

    private static boolean farEnoughFromExistingWater(
        TilePoint point,
        HexCenter center
    ) {
        for (
            int y = point.y - WATER_PATCH_SEPARATION;
            y <= point.y + WATER_PATCH_SEPARATION;
            y++
        ) {
            for (
                int x = point.x - WATER_PATCH_SEPARATION;
                x <= point.x + WATER_PATCH_SEPARATION;
                x++
            ) {
                int deltaX = x - point.x;
                int deltaY = y - point.y;

                if (
                    deltaX * deltaX + deltaY * deltaY
                        > WATER_PATCH_SEPARATION_SQUARED
                ) {
                    continue;
                }

                if (
                    insideLiquidMaskForCenter(x, y, center)
                        && isWater(new TilePoint(x, y))
                ) {
                    return false;
                }
            }
        }

        return true;
    }

    // ---------------------------------------------------------------------
    // Ore guarantees
    // ---------------------------------------------------------------------

    private static void ensureEveryHexHasEveryOre(
        int seed,
        Random random,
        List<HexCenter> centers,
        CorrectionCounter corrections
    ) {
        for (HexCenter center : centers) {
            for (NoisePreset preset : ORE_PRESETS) {
                if (hexContainsOre(center, preset.block)) {
                    continue;
                }

                TilePoint start = bestOreFallbackStart(
                    seed,
                    center,
                    preset,
                    false
                );

                if (start == null) {
                    start = bestOreFallbackStart(
                        seed,
                        center,
                        preset,
                        true
                    );
                }

                if (start == null) {
                    continue;
                }

                int targetSize = inclusiveRandom(
                    random,
                    ORE_FALLBACK_MIN_SIZE,
                    ORE_FALLBACK_MAX_SIZE
                );

                int placed = growOrePatch(
                    seed,
                    preset,
                    center,
                    start,
                    targetSize,
                    ORE_FALLBACK_MAX_LOCAL_RADIUS
                );

                if (placed > 0) {
                    corrections.oreFallbackPatches++;
                }
            }
        }
    }

    private static boolean hexContainsOre(
        HexCenter center,
        Block oreOverlay
    ) {
        for (
            int y = center.y - GUARANTEE_ORE_RADIUS;
            y <= center.y + GUARANTEE_ORE_RADIUS;
            y++
        ) {
            for (
                int x = center.x - GUARANTEE_ORE_RADIUS;
                x <= center.x + GUARANTEE_ORE_RADIUS;
                x++
            ) {
                if (!insideGuaranteeOreMaskForCenter(x, y, center)) {
                    continue;
                }

                Tile tile = Vars.world.tile(x, y);

                if (tile != null && tile.overlay() == oreOverlay) {
                    return true;
                }
            }
        }

        return false;
    }

    private static TilePoint bestOreFallbackStart(
        int seed,
        HexCenter center,
        NoisePreset preset,
        boolean allowOverwrite
    ) {
        TilePoint best = null;
        float bestNoise = -Float.MAX_VALUE;

        for (
            int y = center.y - GUARANTEE_ORE_RADIUS;
            y <= center.y + GUARANTEE_ORE_RADIUS;
            y++
        ) {
            for (
                int x = center.x - GUARANTEE_ORE_RADIUS;
                x <= center.x + GUARANTEE_ORE_RADIUS;
                x++
            ) {
                TilePoint point = new TilePoint(x, y);

                if (
                    canPlaceGuaranteedOre(point, center, allowOverwrite)
                ) {
                    float noise = sample(seed, preset, x, y);

                    if (noise > bestNoise) {
                        bestNoise = noise;
                        best = point;
                    }
                }
            }
        }

        return best;
    }

    // ---------------------------------------------------------------------
    // Noise-guided fallback patch growth
    // ---------------------------------------------------------------------

    private static int growFloorPatch(
        int seed,
        NoisePreset preset,
        HexCenter center,
        TilePoint start,
        Block floor,
        int targetSize,
        int localRadius
    ) {
        PriorityQueue<Candidate> queue = candidateQueue();
        Set<TilePoint> queued = new HashSet<>();
        Set<TilePoint> placed = new HashSet<>();

        queue.add(candidate(seed, preset, start));
        queued.add(start);

        while (!queue.isEmpty() && placed.size() < targetSize) {
            TilePoint point = queue.remove().point;

            if (
                placed.contains(point)
                    || !insideLocalRadius(point, start, localRadius)
                    || !canGrowWaterFallback(point, center)
            ) {
                continue;
            }

            Tile tile = Vars.world.tile(point.x, point.y);
            Tile.setFloor(tile, floor, Blocks.air);
            placed.add(point);

            enqueueNeighbours(seed, preset, point, queue, queued);
        }

        return placed.size();
    }

    private static int growOrePatch(
        int seed,
        NoisePreset preset,
        HexCenter center,
        TilePoint start,
        int targetSize,
        int localRadius
    ) {
        PriorityQueue<Candidate> queue = candidateQueue();
        Set<TilePoint> queued = new HashSet<>();
        Set<TilePoint> placed = new HashSet<>();

        queue.add(candidate(seed, preset, start));
        queued.add(start);

        while (!queue.isEmpty() && placed.size() < targetSize) {
            TilePoint point = queue.remove().point;

            if (
                placed.contains(point)
                    || !insideLocalRadius(point, start, localRadius)
                    || !canPlaceGuaranteedOre(point, center, true)
            ) {
                continue;
            }

            Tile tile = Vars.world.tile(point.x, point.y);
            tile.setOverlay(preset.block);
            placed.add(point);

            enqueueNeighbours(seed, preset, point, queue, queued);
        }

        return placed.size();
    }

    private static PriorityQueue<Candidate> candidateQueue() {
        return new PriorityQueue<>(
            Comparator.comparingDouble((Candidate candidate) -> candidate.noise)
                .reversed()
        );
    }

    private static Candidate candidate(
        int seed,
        NoisePreset preset,
        TilePoint point
    ) {
        return new Candidate(
            point,
            sample(seed, preset, point.x, point.y)
        );
    }

    private static void enqueueNeighbours(
        int seed,
        NoisePreset preset,
        TilePoint point,
        PriorityQueue<Candidate> queue,
        Set<TilePoint> queued
    ) {
        for (int[] direction : DIRECTIONS_8) {
            TilePoint neighbour = new TilePoint(
                point.x + direction[0],
                point.y + direction[1]
            );

            if (queued.add(neighbour)) {
                queue.add(candidate(seed, preset, neighbour));
            }
        }
    }

    // ---------------------------------------------------------------------
    // Placement predicates
    // ---------------------------------------------------------------------

    private static boolean canGrowWaterFallback(
        TilePoint point,
        HexCenter center
    ) {
        Tile tile = Vars.world.tile(point.x, point.y);

        return tile != null
            && tile.block() == Blocks.air
            && tile.floor() == Blocks.darksand
            && insideLiquidMaskForCenter(point.x, point.y, center);
    }

    private static boolean canPlaceGuaranteedOre(
        TilePoint point,
        HexCenter center,
        boolean allowOverwrite
    ) {
        Tile tile = Vars.world.tile(point.x, point.y);

        if (
            tile == null
                || tile.block() != Blocks.air
                || tile.floor() != Blocks.darksand
                || !insideGuaranteeOreMaskForCenter(point.x, point.y, center)
        ) {
            return false;
        }

        return allowOverwrite || tile.overlay() == Blocks.air;
    }

    private static boolean insideOreMask(
        int x,
        int y,
        List<HexCenter> centers
    ) {
        int closestDistanceSquared =
            closestCenterDistanceSquared(x, y, centers);

        return closestDistanceSquared >= ORE_CORE_SAFE_RADIUS_SQUARED
            && closestDistanceSquared <= ORE_MAX_RADIUS_SQUARED;
    }

    private static boolean insideLiquidMask(
        int x,
        int y,
        List<HexCenter> centers
    ) {
        int closestDistanceSquared =
            closestCenterDistanceSquared(x, y, centers);

        return closestDistanceSquared >= LIQUID_CORE_SAFE_RADIUS_SQUARED
            && closestDistanceSquared <= LIQUID_MAX_RADIUS_SQUARED;
    }

    private static boolean insideGuaranteeOreMaskForCenter(
        int x,
        int y,
        HexCenter center
    ) {
        int distanceSquared = squaredDistance(x, y, center.x, center.y);

        return distanceSquared >= ORE_CORE_SAFE_RADIUS_SQUARED
            && distanceSquared <= GUARANTEE_ORE_RADIUS_SQUARED;
    }

    private static boolean insideLiquidMaskForCenter(
        int x,
        int y,
        HexCenter center
    ) {
        int distanceSquared = squaredDistance(x, y, center.x, center.y);

        return distanceSquared >= LIQUID_CORE_SAFE_RADIUS_SQUARED
            && distanceSquared <= LIQUID_MAX_RADIUS_SQUARED;
    }

    private static boolean insideLocalRadius(
        TilePoint point,
        TilePoint start,
        int radius
    ) {
        return squaredDistance(point.x, point.y, start.x, start.y)
            <= radius * radius;
    }

    private static boolean isWater(TilePoint point) {
        Tile tile = Vars.world.tile(point.x, point.y);

        return tile != null && tile.floor() == Blocks.darksandWater;
    }

    private static int closestCenterDistanceSquared(
        int x,
        int y,
        List<HexCenter> centers
    ) {
        int closest = Integer.MAX_VALUE;

        for (HexCenter center : centers) {
            int distanceSquared = squaredDistance(x, y, center.x, center.y);

            if (distanceSquared < closest) {
                closest = distanceSquared;
            }
        }

        return closest;
    }

    // ---------------------------------------------------------------------
    // Noise and reporting helpers
    // ---------------------------------------------------------------------

    private static float sample(
        int baseSeed,
        NoisePreset preset,
        int x,
        int y
    ) {
        /**
         * Mirrors Mindustry editor OreFilter style:
         * noise(x, y + x * tilt, scale, 1, octaves, falloff)
         */
        return Simplex.noise2d(
            baseSeed + preset.seedOffset,
            preset.octaves,
            preset.falloff,
            1f / preset.scale,
            x + 10f,
            y + x * preset.tilt + 10f
        );
    }

    private static int foldSeed(long seed) {
        return (int)(seed ^ (seed >>> 32));
    }

    private static int inclusiveRandom(
        Random random,
        int minimum,
        int maximum
    ) {
        return minimum + random.nextInt(maximum - minimum + 1);
    }

    private static int squaredDistance(
        int x1,
        int y1,
        int x2,
        int y2
    ) {
        int deltaX = x1 - x2;
        int deltaY = y1 - y2;

        return deltaX * deltaX + deltaY * deltaY;
    }

    private static Summary summarizeWorld(CorrectionCounter corrections) {
        int waterTiles = 0;
        int tarTiles = 0;
        int copperTiles = 0;
        int leadTiles = 0;
        int coalTiles = 0;
        int scrapTiles = 0;
        int titaniumTiles = 0;
        int thoriumTiles = 0;

        int width = Vars.world.width();
        int height = Vars.world.height();

        for (int y = 0; y < height; y++) {
            for (int x = 0; x < width; x++) {
                Tile tile = Vars.world.tile(x, y);

                if (tile == null) {
                    continue;
                }

                if (tile.floor() == Blocks.darksandWater) {
                    waterTiles++;
                } else if (tile.floor() == Blocks.tar) {
                    tarTiles++;
                }

                Block overlay = tile.overlay();

                if (overlay == Blocks.oreCopper) {
                    copperTiles++;
                } else if (overlay == Blocks.oreLead) {
                    leadTiles++;
                } else if (overlay == Blocks.oreCoal) {
                    coalTiles++;
                } else if (overlay == Blocks.oreScrap) {
                    scrapTiles++;
                } else if (overlay == Blocks.oreTitanium) {
                    titaniumTiles++;
                } else if (overlay == Blocks.oreThorium) {
                    thoriumTiles++;
                }
            }
        }

        return new Summary(
            waterTiles,
            tarTiles,
            copperTiles,
            leadTiles,
            coalTiles,
            scrapTiles,
            titaniumTiles,
            thoriumTiles,
            corrections.waterFallbackPatches,
            corrections.oreFallbackPatches
        );
    }

    record HexCenter(int x, int y) {
    }

    record Summary(
        int waterTiles,
        int tarTiles,
        int copperTiles,
        int leadTiles,
        int coalTiles,
        int scrapTiles,
        int titaniumTiles,
        int thoriumTiles,
        int waterFallbackPatches,
        int oreFallbackPatches
    ) {
        String compact() {
            return "water=" + waterTiles
                + ", tar=" + tarTiles
                + ", copper=" + copperTiles
                + ", lead=" + leadTiles
                + ", coal=" + coalTiles
                + ", scrap=" + scrapTiles
                + ", titanium=" + titaniumTiles
                + ", thorium=" + thoriumTiles
                + ", waterFallbackPatches=" + waterFallbackPatches
                + ", oreFallbackPatches=" + oreFallbackPatches;
        }
    }

    private record NoisePreset(
        Block block,
        int seedOffset,
        float scale,
        float threshold,
        float octaves,
        float falloff,
        float tilt
    ) {
    }

    private record TilePoint(int x, int y) {
    }

    private record Candidate(TilePoint point, float noise) {
    }

    private static final class CorrectionCounter {
        private int waterFallbackPatches;
        private int oreFallbackPatches;
    }
}
